import type { Theme } from './types';

export const designerThemes: Theme[] = [
  // ─── 1. 温润藏蓝 ──────────────────────────────────
  {
    id: 'warm-navy',
    name: '温润藏蓝',
    description: '暖灰褐底色 + 藏蓝强调，色块卡片式标题，文艺深度内容',
    // Legacy styles fallback (for backward compatibility)
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Noto Sans SC", sans-serif; font-size: 16px; line-height: 1.8; color: #000000; background-color: #ffffff; word-wrap: break-word;',
      h1: 'font-size: 24px; font-weight: 700; color: #14283c; line-height: 1.3; margin: 0 0 16px;',
      h2: 'font-size: 20px; font-weight: 600; color: #14283c; line-height: 1.35; margin: 40px 0 16px;',
      h3: 'font-size: 18px; font-weight: 600; color: #1e1e1e; line-height: 1.4; margin: 32px 0 12px;',
      p: 'margin: 18px 0; line-height: 1.8; color: #000000;',
      strong: 'font-weight: 700; color: #14283c;',
      em: 'font-style: italic; color: #666666;',
      a: 'color: #14283c; text-decoration: none; border-bottom: 1px solid #14283c;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.8; color: #000000;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; background-color: #e5e6e1; border-left: 4px solid #14283c; color: #1e1e1e;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #e5e6e1; color: #14283c; border-radius: 0; font-size: 14px;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #e5e6e1; border-radius: 0; overflow-x: auto; font-size: 14px;',
      hr: 'margin: 40px auto; border: none; height: 1px; background-color: #c8b4a0; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #e5e6e1; padding: 12px 16px; text-align: left; font-weight: 600; color: #14283c; border: 1px solid #c8b4a0;',
      td: 'padding: 12px 16px; border: 1px solid #c8b4a0; color: #000000;',
      tr: 'border: none;',
    },
    // New architecture
    colors: {
      pageBg: '#ffffff',
      textPrimary: '#000000',
      textSecondary: '#1e1e1e',
      accent: '#14283c',
      accentSecondary: '#c8b4a0',
      headingColor: '#14283c',
      linkColor: '#14283c',
      blockquoteBg: '#e5e6e1',
      blockquoteBorder: '#14283c',
      blockquoteText: '#1e1e1e',
      codeBg: '#e5e6e1',
      codeColor: '#14283c',
      tableBorder: '#c8b4a0',
      tableHeaderBg: '#e5e6e1',
      bodyFontSize: 16,
    },
    layout: {
      h1: { align: 'left', decor: 'color-block', decorColor: '#14283c', decorBg: '#e5e6e1', decorRadius: 0, decorWidth: 0 },
      h2: { align: 'left', decor: 'left-bar', decorColor: '#14283c', decorWidth: 4 },
      h3: { align: 'left', decor: 'left-bar', decorColor: '#c8b4a0', decorWidth: 3 },
      image: { borderRadius: 0, shadow: 'none', fullBleed: true, caption: { enabled: true, position: 'below-center', fontSize: 14, color: '#888888' } },
      callout: { variant: 'bg-card', bgColor: '#e5e6e1', padding: 24, marginTop: 24, marginBottom: 24, borderRadius: 0 },
      list: { bulletColor: '#14283c', numberColor: '#14283c', indent: 28 },
      spacing: { paragraphGap: 18, sectionGap: 48, lineHeight: 1.8, contentPadding: { left: 25, right: 25 } },
      divider: { color: '#c8b4a0', height: 1, style: 'solid', marginTop: 40, marginBottom: 40 },
      strong: { color: '#14283c', bgColor: 'transparent' },
    },
  },

  // ─── 2. 蓝红商务 ──────────────────────────────────
  {
    id: 'blue-red',
    name: '蓝红商务',
    description: '软灰正文 + 蓝红色强调，左侧框线标题，专业企业报告风',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Noto Sans SC", sans-serif; font-size: 16px; line-height: 1.8; color: #3c3c3c; background-color: #ffffff; word-wrap: break-word;',
      h1: 'font-size: 24px; font-weight: 700; color: #3c3c3c; line-height: 1.3; margin: 0 0 16px;',
      h2: 'font-size: 20px; font-weight: 600; color: #6996d2; line-height: 1.35; margin: 40px 0 16px;',
      h3: 'font-size: 18px; font-weight: 600; color: #3c3c3c; line-height: 1.4; margin: 32px 0 12px;',
      p: 'margin: 18px 0; line-height: 1.8; color: #3c3c3c;',
      strong: 'font-weight: 700; color: #3c3c3c;',
      em: 'font-style: italic; color: #666666;',
      a: 'color: #6996d2; text-decoration: none; border-bottom: 1px solid #6996d2;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.8; color: #3c3c3c;',
      blockquote: 'margin: 24px 0; padding: 20px 24px; background-color: #eff0eb; border-left: 4px solid #6996d2; color: #3c3c3c;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #eff0eb; color: #c33c2d; border-radius: 0; font-size: 14px;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #eff0eb; border-radius: 0; overflow-x: auto; font-size: 14px;',
      hr: 'margin: 40px auto; border: none; height: 1px; background-color: #e5e5e5; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #eff0eb; padding: 12px 16px; text-align: left; font-weight: 600; color: #3c3c3c; border: 1px solid #d5d6d2;',
      td: 'padding: 12px 16px; border: 1px solid #d5d6d2; color: #3c3c3c;',
      tr: 'border: none;',
    },
    colors: {
      pageBg: '#ffffff',
      textPrimary: '#3c3c3c',
      textSecondary: '#464646',
      accent: '#6996d2',
      accentSecondary: '#c33c2d',
      headingColor: '#3c3c3c',
      linkColor: '#6996d2',
      blockquoteBg: '#eff0eb',
      blockquoteBorder: '#6996d2',
      blockquoteText: '#3c3c3c',
      codeBg: '#eff0eb',
      codeColor: '#c33c2d',
      tableBorder: '#d5d6d2',
      tableHeaderBg: '#eff0eb',
      bodyFontSize: 16,
    },
    layout: {
      h1: { align: 'left', decor: 'none' },
      h2: { align: 'left', decor: 'left-bar', decorColor: '#6996d2', decorWidth: 4 },
      h3: { align: 'left', decor: 'colored-text', decorColor: '#6996d2' },
      image: { borderRadius: 0, shadow: 'none', fullBleed: true, caption: { enabled: true, position: 'below-center', fontSize: 14, color: '#888888' } },
      callout: { variant: 'subtle-card', bgColor: '#eff0eb', padding: 20, marginTop: 24, marginBottom: 24, borderRadius: 0 },
      list: { bulletColor: '#6996d2', numberColor: '#3c3c3c', indent: 28 },
      spacing: { paragraphGap: 18, sectionGap: 40, lineHeight: 1.8, contentPadding: { left: 25, right: 25 } },
      divider: { color: '#e5e5e5', height: 1, style: 'solid', marginTop: 40, marginBottom: 40 },
      strong: { color: '#3c3c3c', bgColor: 'transparent' },
    },
  },

  // ─── 3. 橙蓝极简 ──────────────────────────────────
  {
    id: 'orange-blue',
    name: '橙蓝极简',
    description: '纯黑文字 + 橙蓝双色边框，高对比编辑风，适合观点论述',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Noto Sans SC", sans-serif; font-size: 16px; line-height: 1.8; color: #000000; background-color: #ffffff; word-wrap: break-word;',
      h1: 'font-size: 24px; font-weight: 700; color: #000000; line-height: 1.3; margin: 0 0 16px;',
      h2: 'font-size: 20px; font-weight: 600; color: #000000; line-height: 1.35; margin: 40px 0 16px; padding-left: 12px; border-left: 4px solid #e15a1e;',
      h3: 'font-size: 18px; font-weight: 600; color: #000000; line-height: 1.4; margin: 32px 0 12px;',
      p: 'margin: 18px 0; line-height: 1.8; color: #000000;',
      strong: 'font-weight: 700; color: #e15a1e;',
      em: 'font-style: italic; color: #666666;',
      a: 'color: #3c69e1; text-decoration: none; border-bottom: 1px solid #3c69e1;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.8; color: #000000;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; border-left: 4px solid #e15a1e; color: #000000; background-color: transparent;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f5f5f5; color: #e15a1e; border-radius: 0; font-size: 14px;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f5f5f5; border-radius: 0; overflow-x: auto; font-size: 14px;',
      hr: 'margin: 40px auto; border: none; height: 1px; background-color: #e5e5e5; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f5f5f5; padding: 12px 16px; text-align: left; font-weight: 600; color: #000000; border: 1px solid #e5e5e5;',
      td: 'padding: 12px 16px; border: 1px solid #e5e5e5; color: #000000;',
      tr: 'border: none;',
    },
    colors: {
      pageBg: '#ffffff',
      textPrimary: '#000000',
      textSecondary: '#141414',
      accent: '#e15a1e',
      accentSecondary: '#3c69e1',
      headingColor: '#000000',
      linkColor: '#3c69e1',
      blockquoteBg: 'transparent',
      blockquoteBorder: '#e15a1e',
      blockquoteText: '#000000',
      codeBg: '#f5f5f5',
      codeColor: '#e15a1e',
      tableBorder: '#e5e5e5',
      tableHeaderBg: '#f5f5f5',
      bodyFontSize: 16,
    },
    layout: {
      h1: { align: 'left', decor: 'none' },
      h2: { align: 'left', decor: 'left-bar', decorColor: '#e15a1e', decorWidth: 4 },
      h3: { align: 'left', decor: 'left-bar', decorColor: '#3c69e1', decorWidth: 3 },
      image: { borderRadius: 0, shadow: 'none', fullBleed: true, caption: { enabled: true, position: 'below-center', fontSize: 14, color: '#888888' } },
      callout: { variant: 'left-border', borderColor: '#e15a1e', borderWidth: 4, padding: 16, marginTop: 24, marginBottom: 24, borderRadius: 0 },
      list: { bulletColor: '#e15a1e', numberColor: '#000000', indent: 28 },
      spacing: { paragraphGap: 18, sectionGap: 48, lineHeight: 1.8, contentPadding: { left: 25, right: 25 } },
      divider: { color: '#e5e5e5', height: 1, style: 'solid', marginTop: 40, marginBottom: 40 },
      strong: { color: '#e15a1e', bgColor: 'transparent' },
    },
  },

  // ─── 4. 绿蓝企业 ──────────────────────────────────
  {
    id: 'green-blue',
    name: '绿蓝企业',
    description: '深灰正文 + 绿蓝边框，绿色信任感 + 蓝色权威感，企业研报',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Noto Sans SC", sans-serif; font-size: 16px; line-height: 1.8; color: #3c3c3c; background-color: #ffffff; word-wrap: break-word;',
      h1: 'font-size: 24px; font-weight: 700; color: #3c3c3c; line-height: 1.3; margin: 0 0 16px;',
      h2: 'font-size: 20px; font-weight: 600; color: #3c3c3c; line-height: 1.35; margin: 40px 0 16px; padding-left: 12px; border-left: 4px solid #4bb469;',
      h3: 'font-size: 18px; font-weight: 600; color: #3c3c3c; line-height: 1.4; margin: 32px 0 12px;',
      p: 'margin: 18px 0; line-height: 1.8; color: #3c3c3c;',
      strong: 'font-weight: 700; color: #4bb469;',
      em: 'font-style: italic; color: #666666;',
      a: 'color: #0f0fd2; text-decoration: none; border-bottom: 1px solid #0f0fd2;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.8; color: #3c3c3c;',
      blockquote: 'margin: 24px 0; padding: 16px 20px; border-left: 4px solid #4bb469; color: #3c3c3c; background-color: transparent;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f5f5f5; color: #4bb469; border-radius: 0; font-size: 14px;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f5f5f5; border-radius: 0; overflow-x: auto; font-size: 14px;',
      hr: 'margin: 40px auto; border: none; height: 1px; background-color: #e5e5e5; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #f0faf2; padding: 12px 16px; text-align: left; font-weight: 600; color: #3c3c3c; border: 1px solid #d0e8d4;',
      td: 'padding: 12px 16px; border: 1px solid #d0e8d4; color: #3c3c3c;',
      tr: 'border: none;',
    },
    colors: {
      pageBg: '#ffffff',
      textPrimary: '#3c3c3c',
      textSecondary: '#464646',
      accent: '#4bb469',
      accentSecondary: '#0f0fd2',
      headingColor: '#3c3c3c',
      linkColor: '#0f0fd2',
      blockquoteBg: 'transparent',
      blockquoteBorder: '#4bb469',
      blockquoteText: '#3c3c3c',
      codeBg: '#f5f5f5',
      codeColor: '#4bb469',
      tableBorder: '#d0e8d4',
      tableHeaderBg: '#f0faf2',
      bodyFontSize: 16,
    },
    layout: {
      h1: { align: 'left', decor: 'none' },
      h2: { align: 'left', decor: 'left-bar', decorColor: '#4bb469', decorWidth: 4 },
      h3: { align: 'left', decor: 'left-bar', decorColor: '#0f0fd2', decorWidth: 3 },
      image: { borderRadius: 0, shadow: 'none', fullBleed: true, caption: { enabled: true, position: 'below-center', fontSize: 14, color: '#888888' } },
      callout: { variant: 'left-border', borderColor: '#4bb469', borderWidth: 4, padding: 16, marginTop: 24, marginBottom: 24, borderRadius: 0 },
      list: { bulletColor: '#4bb469', numberColor: '#3c3c3c', indent: 28 },
      spacing: { paragraphGap: 18, sectionGap: 40, lineHeight: 1.8, contentPadding: { left: 25, right: 25 } },
      divider: { color: '#e5e5e5', height: 1, style: 'solid', marginTop: 40, marginBottom: 40 },
      strong: { color: '#4bb469', bgColor: 'transparent' },
    },
  },

  // ─── 5. 亮黄重点 ──────────────────────────────────
  {
    id: 'yellow-highlight',
    name: '亮黄重点',
    description: '大黄底色 Callout 块，极强视觉停顿，适合关键信息强调',
    styles: {
      container: 'max-width: 100%; margin: 0 auto; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Noto Sans SC", sans-serif; font-size: 16px; line-height: 1.75; color: #3c3c3c; background-color: #ffffff; word-wrap: break-word;',
      h1: 'font-size: 26px; font-weight: 700; color: #3c3c3c; line-height: 1.3; margin: 0 0 16px;',
      h2: 'font-size: 20px; font-weight: 600; color: #3c3c3c; line-height: 1.35; margin: 40px 0 16px;',
      h3: 'font-size: 18px; font-weight: 600; color: #3c3c3c; line-height: 1.4; margin: 32px 0 12px;',
      p: 'margin: 18px 0; line-height: 1.75; color: #3c3c3c;',
      strong: 'font-weight: 700; color: #000000; background-color: #f0f04b; padding: 2px 6px;',
      em: 'font-style: italic; color: #666666;',
      a: 'color: #3c69e1; text-decoration: none; border-bottom: 1px solid #3c69e1;',
      ul: 'margin: 16px 0; padding-left: 28px;',
      ol: 'margin: 16px 0; padding-left: 28px;',
      li: 'margin: 8px 0; line-height: 1.75; color: #3c3c3c;',
      blockquote: 'margin: 24px 0; padding: 24px 28px; background-color: #f0f04b; color: #3c3c3c; border-left: none;',
      code: 'font-family: "SF Mono", Consolas, monospace; padding: 3px 6px; background-color: #f0f04b; color: #3c3c3c; border-radius: 0; font-size: 14px;',
      pre: 'margin: 24px 0; padding: 20px; background-color: #f5f5f5; border-radius: 0; overflow-x: auto; font-size: 14px;',
      hr: 'margin: 40px auto; border: none; height: 1px; background-color: #e5e5e5; width: 100%;',
      img: 'max-width: 100%; height: auto; display: block; margin: 24px auto;',
      table: 'width: 100%; margin: 24px 0; border-collapse: collapse; font-size: 15px;',
      th: 'background-color: #fef9d7; padding: 12px 16px; text-align: left; font-weight: 600; color: #3c3c3c; border: 1px solid #e5e5e5;',
      td: 'padding: 12px 16px; border: 1px solid #e5e5e5; color: #3c3c3c;',
      tr: 'border: none;',
    },
    colors: {
      pageBg: '#ffffff',
      textPrimary: '#3c3c3c',
      textSecondary: '#000000',
      accent: '#f0f04b',
      accentSecondary: '#3c69e1',
      headingColor: '#3c3c3c',
      linkColor: '#3c69e1',
      blockquoteBg: '#f0f04b',
      blockquoteBorder: 'transparent',
      blockquoteText: '#3c3c3c',
      codeBg: '#f0f04b',
      codeColor: '#3c3c3c',
      tableBorder: '#e5e5e5',
      tableHeaderBg: '#fef9d7',
      bodyFontSize: 16,
    },
    layout: {
      h1: { align: 'left', decor: 'none' },
      h2: { align: 'left', decor: 'none' },
      h3: { align: 'left', decor: 'none' },
      image: { borderRadius: 0, shadow: 'none', fullBleed: true, caption: { enabled: true, position: 'below-center', fontSize: 14, color: '#888888' } },
      callout: { variant: 'bg-card', bgColor: '#f0f04b', padding: 24, marginTop: 24, marginBottom: 24, borderRadius: 0 },
      list: { bulletColor: '#f0f04b', numberColor: '#3c3c3c', indent: 28 },
      spacing: { paragraphGap: 18, sectionGap: 40, lineHeight: 1.75, contentPadding: { left: 25, right: 25 } },
      divider: { color: '#e5e5e5', height: 1, style: 'solid', marginTop: 40, marginBottom: 40 },
      strong: { color: '#000000', bgColor: '#f0f04b', padding: '2px 6px', borderRadius: '0' },
    },
  },
];
